### ISSUE TITLE
Issues with special characters in regexp.

### ISSUE THREAD

**Issue by begrs** [kulibali/ironmeta#26]
I have a lot of trouble getting IronMeta to work as expected with the regular expressions:
Issue cases: 
-   \s does not match \n and some other whitespace characters -> this is on verophyle.regexp, not iron meta
-  `CustomString = /[^\"]/;` This works, but gets a weird syntax highlighting in VS Code if you set it to c# because the " starts a new string. 
- /REGEXPCODE/*  is legal in the grammar but makes everything behind it be displayed as a comment in VS Code with c# syntax highlighting
-  it is not possible to have newline \n or tab \t inside of a regexp. 

The reason for the latter is the following:
`ws = /[\t \n\r]*/;`  This is my rule to match zero or more whitespace characters in the .ironmeta file. This gets parsed into `new Verophyle.Regexp.StringRegexp(@"[\t \n\r]*")` which looks fine at first. Actually it does not work due to the @ in front of the string which disables the tab and newline escapes. 

Proposal:
move away from the `/REGEXPCODE/` syntax and use a c# string with a special prefix to label it as a regexp. e.g. `§"REGEXPCODE"` which would be `ws = §"[\t \n\r]*";` for my ws.  This has the benefit of being interpreted as a string so \t, \r and \n should work as intended while also being nicely displayed in VS Code with c# syntax highlighting.
If this is not to your liking, another way to input special characters is needed. Another option would be to provide the special characters (especially not visible once like the tab and newline) to be input via unicode encoding which could look something like this: `\u12345`

**Comment by kulibali** [comment]
Thanks for the feedback!

- I have made a new version of `Verophyle.Regexp` that fixes the bug where `\s` does not match control characters, and updated IronMeta to version 4.4.3.
- As for syntax highlighting, IronMeta is not C#.  It can contain snippets of C#, but the idea is to allow snippets of other languages in the future, so I'm hesitant to tie it too closely to C# syntax.
- It is perfectly possible to use `\n` or `\t` in a regexp.  The raw string in C# doesn't matter, because the regexp library will parse the escapes itself.  Please see the test `TestWhitespaceInRegexp_Issue_26` (and its associated file `RegexpParser.ironmeta`) which confirms this.
- It has always been possible to use Unicode in a regexp.  The syntax is `\u{0abc}`.  See the test `TestUnicodeInRegexp_Issue_26` which confirms this.
