### ISSUE TITLE
General Question: Parse anything

### ISSUE THREAD

**Issue by furesoft** [kulibali/ironmeta#29]
hi, i would parse a block with body that can be anything, like this:
xml { <root /> }

this works fine but when i want to try some body content with curly braces it fails:
json { "obj": { "key": true } }

my rule for the body: [^}]*
ive treid using .* instead but it matches the end curly brace of the root block.

how could i solve this?

**Comment by kulibali** [comment]
You need to consider inner objects recursively.  The following grammar might work:

    ironmeta Grammar<char, int> : Matcher<char, int>
    {
        JsonObjectString = '{' (JsonObjectString | JsonString | ~'}' .)* '}';
        JsonString = '"' (~'\"' .)* '"';
    }

The first rule says, "Match a '{', then either: an inner object, or a string (because there could be a '}' inside a string), or any character that is not '}'; then match '}'.

If you are merely trying to recognize JSON (i.e. tell if a string is valid JSON or not), this would suffice.

If you are trying to parse JSON, you'll need something more semantically oriented.

**Comment by furesoft** [comment]
i dont want to parse json. i want to get all content out of the {} block.
